### ISSUE TITLE
how to listen cordova's backbutton event

### ISSUE THREAD

**Issue by ijry** [scriptPilot/app-framework#618] opened 2017-06-29 04:25 UTC
where can i put this code
`document.addEventListener("backbutton", onBackKeyDown, false);`

**Comment by Grogglex** [comment] 2017-06-29 15:04
You can put it in the `mounted` hook of your app.vue but you want to have a `deviceReady` callback first.

**Comment by Grogglex** [comment] 2017-06-29 15:04
Something like this:
```

    if (global.cordova) {
      document.addEventListener('deviceready', function () {
        setupService.setupCordova()
      })
    } else {
      setupService.setupBrowser()
    }

```

**Comment by scriptPilot** [comment] 2017-07-02 16:11
@ijry @Grogglex - You dont have to add the listener, you can use Cordova hooks in any .vue file. Framework7 will be initialized AFTER Cordova.

**Closed by scriptPilot** 2017-07-02 16:11 UTC
Labels: question

**Comment by ijry** [comment] 2017-07-02 16:30
can you make a example thks.

**Comment by scriptPilot** [comment] 2017-07-03 04:39
```
<script>
  export default {
    mounted() {
      ... your code
    }
  }
</script>
```

**Comment by ijry** [comment] 2017-07-05 02:06
![default](https://user-images.githubusercontent.com/3102798/27846387-8e76bc08-6169-11e7-902c-27b4b3727133.PNG)
 can not work!

**Comment by scriptPilot** [comment] 2017-07-05 07:11
I see in the Cordova docs:

- https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.backbutton.html
- This version of the documentation is outdated! (v4, no newer available)

Supported platforms:

Amazon Fire OS
Android
BlackBerry 10
Windows Phone 8

So ... without any details (your system, steps to reproduce ...) no way to help.

**Comment by ijry** [comment] 2017-07-05 07:43
i start my app with this  project  [https://github.com/centrual/cordova-template-framework7-vue-webpack](https://github.com/centrual/cordova-template-framework7-vue-webpack)  , question is how to bind android's backbutton to f7's  router's back?

**Comment by ijry** [comment] 2017-07-05 07:48
if I set pushState:true, then the back will work, but I want set it flase with the back also work.

**Comment by ijry** [comment] 2017-07-05 07:58
can you help me with this issue 
[https://github.com/nolimits4web/Framework7-Vue/issues/201](https://github.com/nolimits4web/Framework7-Vue/issues/201)
[https://github.com/nolimits4web/Framework7-Vue/issues/202](https://github.com/nolimits4web/Framework7-Vue/issues/202)
thks!!!

**Comment by scriptPilot** [comment] 2017-07-05 08:58
@ijry - All three links are to different repos, not App Framework related I would say.

**Comment by ijry** [comment] 2017-07-05 13:06
I know , but i can see the two repo are very close, since the other's has no one reply me ,I need you help, thks.

**Comment by Grogglex** [comment] 2017-07-12 16:14
The way I did it ijry is in my app.vue's `methods` I put this method:

```
// Setup code that fires when framework7 (router, etc) is ready
onF7Init () { 
  if(global.cordova)
  document.addEventListener('backbutton', this.$root.$f7Router.framework7.mainView.router.back, false)
},

```

```

**Comment by monsterdream** [comment] 2017-07-23 16:52
Hmm I need to admit that for me part with document.addEventListener('deviceready' is also not working, strange things. I'm testing it on emulator and real devices but it seems that it's completely not responding.

```
      methods: {
        onF7Init: function () {
          let vm = this
            document.addEventListener('deviceready', function () {
              vm .$f7.alert('App is mounted!')
            }, false)
          }
}
```
There is no any magic, it should work. Idea with if(global.cordova) also not helping.

**Comment by scriptPilot** [comment] 2017-07-23 18:36
@monsterdream - F7 init is done after deviceready event, so, you do not have to listen and you could use all cordova commands right now.

**Comment by strevecloud** [comment] 2017-10-29 11:32
i try this one but not working, could you give me a sample for back button event?

```
export default{
  mouted () {
    document.addEventListener('backbutton', onBackKeyDown, false)

    function onBackKeyDown (e) {
      e.preventDefault()
      alert('Back Button is Pressed!')
    }
```
  }
}

**Comment by scriptPilot** [comment] 2017-10-29 12:07
Try with `mounted()` instead of `mouted()`

**Comment by strevecloud** [comment] 2017-10-29 13:56
its work, sory typo 👍 but how to go back?

`if (window.location.href !== '/home') {
        window.history.back();
    } else {
        throw new Error('Exit'); 
    }`
this code is not working

**Comment by scriptPilot** [comment] 2017-10-29 19:05
Please read the F7-Vue docu: https://framework7.io/vue/navigation-router.html

**Comment by strevecloud** [comment] 2017-10-30 18:08
yeah but i use this.$f7.views.main.router.back() in app vue is not working, but when i just place alert there is working correcly, i try to put this.$router.back() in custom page components it not working,\
thanks b4

**Comment by fdbeirao** [comment] 2017-11-20 11:16
Was there any solution to this issue? 

I am trying to also listen for the `backbutton`, and (naively) try to "navigate back" (my app is still very early stages). 

This is motivated by the fact that the demo app (in play store) has a very strange behaviour for Android users, where you press the device's `back` button, and the application simply "exits". This is not the expected behavior for an Android user.


This is the code I have put on `app.vue` (this is still very vanilla app-framework, just after npm install):
```javascript
<script>
function navigateBack() {
  // Use Framework7's router to navigate back
  this.$f7.mainView.router.back()
}

export default {
  mounted() {
    // Listen to Cordova's backbutton event
    document.addEventListener('backbutton', navigateBack, false)
  },
}
</script>
```

I am running the app on my physical android device. These are the errors on console (accessible through `chrome://inspect` on my desktop machine):

```
init.55d8c78.js:1 Uncaught TypeError: window.Dom7 is not a function
    at init.55d8c78.js:1
    at o (init.55d8c78.js:1)
    at HTMLScriptElement.n.onload (init.55d8c78.js:1)

app.55d8c78.js:15 Uncaught TypeError: Cannot read property 'mainView' of undefined
    at Channel.a (app.55d8c78.js:15)
    at Channel.fire (cordova.js:847)
    at cordova.js:232
```

Any hints on how to proceed? Thank you :)

**Comment by zevai** [comment] 2017-11-20 15:37
This works for me (in app.vue):

    <script>
      export default {
        methods: {
            onF7Init: function () {
                if(global.cordova)
                document.addEventListener('backbutton', this.$root.$f7Router.framework7.mainView.router.back, false)
            }
        }
      }
    </script>

Android back button works as native in my app.

**Comment by strevecloud** [comment] 2017-11-20 16:40
@zevai thanks a lot  its work for me, but how to exit app in homepage?

**Comment by zevai** [comment] 2017-11-20 18:13
@strevecloud I think you could try [cordova-plugin-exitapp](https://www.npmjs.com/package/cordova-plugin-exitapp). Check the current route and if it is your homepage, use `navigator.app.exitApp();`
You have to install plugin first and declare it in config, as described [here](https://github.com/scriptPilot/app-framework/blob/master/docs/cordova-plugins.md).

**Comment by dilawar** [comment] 2019-04-02 12:20
I tried various things on this thread, none worked for me. My app is almost ready to launch but can't get back button to behave well.
